from sqlalchemy import Column, Integer, String, Boolean
from src.Config.Database.db import Base

class C100(Base):
    __tablename__ = "c100"

    id = Column(Integer, primary_key=True, index=True)
    empresa_id = Column(Integer, index=True)
    periodo = Column(String(10))
    reg = Column(String(10))
    ind_oper = Column(String(5))
    ind_emit = Column(String(5))
    cod_part = Column(String(60))
    cod_mod = Column(String(10))
    cod_sit = Column(String(10))
    ser = Column(String(10))
    num_doc = Column(String(20))
    chv_nfe = Column(String(60))
    dt_doc = Column(String(10))
    dt_e_s = Column(String(10))
    vl_doc = Column(String(20))
    ind_pgto = Column(String(5))
    vl_desc = Column(String(20))
    vl_abat_nt = Column(String(20))
    vl_merc = Column(String(20))
    ind_frt = Column(String(5))
    vl_frt = Column(String(20))
    vl_seg = Column(String(20))
    vl_out_da = Column(String(20))
    vl_bc_icms = Column(String(20))
    vl_icms = Column(String(20))
    vl_bc_icms_st = Column(String(20))
    vl_icms_st = Column(String(20))
    vl_ipi = Column(String(20))
    vl_pis = Column(String(20))
    vl_cofins = Column(String(20))
    vl_pis_st = Column(String(20))
    vl_cofins_st = Column(String(20))
    filial = Column(String(10))
    is_active = Column(Boolean, nullable=False, default=True)
