from sqlalchemy import Column, Integer, String
from Config.Database.db import Base

class C170(Base):
    __tablename__ = "c170"

    id = Column(Integer, primary_key=True, index=True)
    empresa_id = Column(Integer, index=True)
    periodo = Column(String(10))
    reg = Column(String(10))
    num_item = Column(String(10))
    cod_item = Column(String(60))
    descr_compl = Column(String(255))
    qtd = Column(String(20))
    unid = Column(String(10))
    vl_item = Column(String(20))
    vl_desc = Column(String(20))
    ind_mov = Column(String(5))
    cst_icms = Column(String(10))
    cfop = Column(String(10))
    cod_nat = Column(String(11))
    vl_bc_icms = Column(String(20))
    aliq_icms = Column(String(10))
    vl_icms = Column(String(20))
    vl_bc_icms_st = Column(String(20))
    aliq_st = Column(String(10))
    vl_icms_st = Column(String(20))
    ind_apur = Column(String(5))
    cst_ipi = Column(String(10))
    cod_enq = Column(String(10))
    vl_bc_ipi = Column(String(20))
    aliq_ipi = Column(String(10))
    vl_ipi = Column(String(20))
    cst_pis = Column(String(10))
    vl_bc_pis = Column(String(20))
    aliq_pis = Column(String(10))
    quant_bc_pis = Column(String(20))
    aliq_pis_reais = Column(String(20))
    vl_pis = Column(String(20))
    cst_cofins = Column(String(10))
    vl_bc_cofins = Column(String(20))
    aliq_cofins = Column(String(10))
    quant_bc_cofins = Column(String(20))
    aliq_cofins_reais = Column(String(20))
    vl_cofins = Column(String(20))
    cod_cta = Column(String(255))
    vl_abat_nt = Column(String(20))
    id_c100 = Column(Integer)
    filial = Column(String(10))
    ind_oper = Column(String(5))
    cod_part = Column(String(60))
    num_doc = Column(String(20))
    chv_nfe = Column(String(60))
    ncm = Column(String(44), default='')
    mercado = Column(String(15), default='')
    aliquota = Column(String(10), default='')
    resultado = Column(String(20))
